### PR TITLE
Sample code and build instructions

### PR DESCRIPTION
**Pull request by marians**
Feld like contributing a piece of code :)

The code has one dependency, which is also mentioned in the README in the build/dependencies part.

### CODE REVIEW

**Comment by marians** [comment]
Ping @puja108

**Comment by puja108** [comment]
ok by me, would help us with doing examples with CI, too. Just will need to merge the readme changes into the other readme PR, but that's ok ;)

**Comment by puja108** [comment]
and LGTM ;)

**Comment by marians** [comment]
Thanks!

**Pull request merged**
