### PR TITLE
added godoc and dockherhub pulls shields/badges

### PR DESCRIPTION
**Pull request by puja108**

### CODE REVIEW

**Comment by puja108** [comment]
RFR @marians 

I used `mayu` as an example for now, as that's where we're gonna use it first, but we can generalize this before merging

**Comment by marians** [comment]
Why not use

https://godoc.org/github.com/giantswarm/example-opensource-repo?status.svg
https://img.shields.io/docker/pulls/giantswarm/example-opensource-repo.svg

**Comment by puja108** [comment]
changed, did we create an autobuild for this or push to dockerhub? the badge is not working

**Comment by marians** [comment]
It's autobuild. The dockerhub badges are sometimes unresponsive, but that's nothing we can solve.

**Comment by marians** [comment]
LGTM

**Comment by puja108** [comment]
yeah, seems like the API is down quite often

**Pull request merged**
