### PR TITLE
Adding IRC shield to README

### PR DESCRIPTION
**Pull request by marians**
RFR @puja108 

Might not work currently, since shields.io has some problems.

Preview: 

image

### CODE REVIEW

**Comment by puja108** [comment]
yup, it's greyed out, but I do like the idea, we should definitely do it!

**Comment by marians** [comment]
> yup, it's greyed out

What does that mean? I intentionally set the color to grey, to distinguish it from the status shields, where color has a meaning.

**Comment by puja108** [comment]
hmm, I thought grey usually means it doesn't work, intuitively at least it feels to me like that, maybe a different color?

**Comment by puja108** [comment]
other than the color (not sure about that) LGTM

**Comment by marians** [comment]
OK, makes sense. Changed the color to blue.

**Pull request merged**
